x-repo:
  &services-repo
  type: bind
  source: "/home/guy/Code/c3s-attribution/"
  target: /code

x-storage:
  &services-storage
  type: bind
  source: "/home/guy/Data/c3s-attribution/"
  target: /data


services:

  c3spy:
    image: c3spy
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./Dockerfile.python
      args:
        - CUSTOM_ENV=pyenv.yml
    stdin_open: true
    tty: true
    volumes:
    - *services-repo
    - *services-storage
    command: bash
  
  # ncwms:
  #   image: ncwms
  #   platform: "linux/amd64"
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile.ncwms2
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #   - *services-storage
