name: c3s-pyenv
channels:
  - conda-forge
dependencies:
  - python
  - xarray
  - netcdf4
  - zarr
  - conda-pack
  - numpy
  - dask
  - geopandas
  - fiona
  - shapely
  - rasterio
  - geopy
  - beautifulsoup4
  - scikit-learn
  - scipy
  - cdsapi
  - pip
  - pip:
      - hdbscan
