import { TimeLocaleDefinition } from 'd3'
import { App, computed, ComputedRef, inject, InjectionKey } from 'vue'

const langNames: Record<Language, string> = {
	en: 'English',
}

const labelsEn = {
	title: 'Extremes ERA',
	events: 'Events',
	help: 'Help',
	aboutInfo: 'About this tool',
	duration: 'Duration (days)',
	time: 'Date',
	from: 'From',
	to: 'To',
	size: 'Area (km²)',
	temperature: 'Temperature (°C)',
	wetIndex: 'Wet day index',
	download: 'Download',
	showTimePanel: 'Show time panel',
	hideTimePanel: 'Hide time panel',
	filter: 'Filter events',
	nextDay: 'Next day',
	prevDay: 'Previous day',
	endOfYear: 'End of year',
	startOfYear: 'Start of year',
	beyondDataLimit: 'Beyond data limit',
	nextTimestep: 'Step forward',
	prevTimestep: 'Step backward',
	endOfTimeline: 'End of events',
	startOfTimeline: 'Start of events',
	startOfEvent: 'Start of event',
	endOfEvent: 'End of event',
	nextYear: 'Next year',
	prevYear: 'Previous year',
	play: 'Play',
	pause: 'Pause',
	startHandle: 'Adjust start date',
	grabHandle: 'Move the selected date range',
	endHandle: 'Adjust end date',
	closeFocusFrame: 'Close event details',
	zoomIn: 'Zoom in',
	zoomOut: 'Zoom out',
	resetZoom: 'Reset zoom',
	hamburger: 'Filters and settings',
	exploreGlobal: 'Explore global events',
	selectByPoint: 'Explore events at a point',
	selectByRegion: 'Explore events in a region',
	selectTimeMachineMode: 'Time Machine - explore events over time',
	selectHeatmapMode: 'Overview - explore events by location',
	lessThan: 'less than or equal to',
	greaterThan: 'greater than or equal to',
	resetFilter: 'Reset filter',
	switchTo: 'Switch to',
	durationNumberOfDays: 'Enter duration for filter',
	sizeNumberOfSquareKilometers: 'Enter size in km² for filter',
	tempNumberOfDegrees: 'Enter temperature in °C for filter',
	wetIndexFilter: 'Enter wet day index for filter',
	selectAllTemperatureEvents: 'Explore all extreme temperature events',
	selectHeatwaveEvents: 'Explore extreme heat events',
	selectColdwaveEvents: 'Explore extreme cold events',
	selectWetwaveEvents: 'Explore extreme wet events',
	selectHotWetEvents: 'Explore extreme hot and wet events',
	selectColdWetEvents: 'Explore extreme cold and wet events',
	heatwaveEvents: 'extreme heat events',
	coldwaveEvents: 'extreme cold events',
	wetwaveEvents: 'extreme wet events',
	allTemperatureEvents: 'extreme temperature events',
	allWetEvents: 'extreme wet events',
	rankingForTopEvents: 'Ranking for top events',
	rankingForTop100Events: 'Ranking for top 100 events',
	cycleSortVariable: 'click to cycle variable',
	rankedByDuration: 'Ranked by duration',
	rankedBySize: 'Ranked by size',
	rankedByTemp: 'Ranked by temperature',
	rankedByWetIndex: 'Ranked by wet day index',
	hotTitle: 'Heatwave Events',
	coldTitle: 'Cold Events',
	wetTitle: 'Wet Events',
	hotcoldTitle: 'Temperature Events',
	hotwetTitle: 'Hot and Wet Events',
	coldwetTitle: 'Cold and Wet Events',
	wetLabel: 'Wet day index',
	wetIntensityLabel: 'Wet day index',
	intensity: 'Intensity',
	intensityNumberOfDegrees: 'Enter intensity value for filter',
	rankedByIntensity: 'Ranked by intensity',
	eventMax: 'Max. event value',
	eventMin: 'Min. event value',
	sortAscending: 'Sort ascending (currently sorted descending)',
	sortDescending: 'Sort descending (currently sorted ascending)',
	eventsOn: 'events on',
	eventsOver: 'events over the period',
	close: 'Close',
	multiEventPanel: 'Show multi-event charts',
	multiEventPanelTitle: 'Multiple event summaries',
	eventInformation: 'Event information',
	maximiseMultiEventPanel: 'Expand multi-event panel',
	restoreMultiEventPanel: 'Shrink multi-event panel',
	showInfoPanel: 'Events summary',
	showOverview: 'Explore full timeline',
	showEventBars: 'Show individual events',
	hideEventBars: 'Hide individual events',
	downloadEventData: 'Download event data as JSON',
	minTemp: 'Minimum Temperature',
	maxTemp: 'Maximum Temperature',
	minTempDaily: 'Daily Minimum Temperature (°C)',
	meanTempDaily: 'Daily Mean Temperature (°C)',
	maxTempDaily: 'Daily Maximum Temperature (°C)',
	maxWetDaily: 'Daily Maximum Wet Day Index',
	minWetDaily: 'Daily Minimum Wet Day Index',
	meanWetDaily: 'Daily Mean Wet Day Index',
	pixelCount: 'Number of grid cells',
	pixelDistDailyTemp: 'Histogram of daily grid cell temperature',
	pixelDistDailyWet: 'Histogram of daily grid cell wet day index',
	durationHisto: 'Event distribution by duration',
	tempHisto: 'Event distribution by temperature',
	wetHisto: 'Event distribution by wet day index',
	sizeHisto: 'Event distribution by area',
	durationTimeSeries: 'Event durations over time',
	sizeTimeSeries: 'Event areas over time',
	tempTimeSeries: 'Event temperatures over time',
	wetTimeSeries: 'Event wet day indices over time',
	sizeDaily: 'Daily Event Area (sq. km)',
	reportId: 'Associated attribution report',
	focusOnMostEvents: 'Show most events',
	focusOnAllEvents: 'Show all events',
	focusOnSelectedEvent: 'Focus on selected event',
	showSensibleView: 'Sensible zoom (hide outliers)',
	showOutliers: 'Show outliers (full range)',
	followSelectedEvent: 'Keep selected event in view',
	resetView: 'Reset zoom',
	eventTempTS: 'Event Temperature by Day',
	eventWetTS: 'Event Wet Day Index by Day',
	eventSizeTS: 'Event Area by Day',
	nEvents: 'Number of Events',
	nEventsShort: 'Events',
	chooseEventType: 'Choose event type to explore',
	chooseFilters: 'Choose filters to apply to events',
	loading: 'Loading data...',
	noEvents: 'No events found for the selected filters and time range.',
	welcome: 'Show welcome information',
	cellTemp: 'Temperature of grid cell',
	cellWet: 'Wet day index of grid cell',
	eventMaxTemp: 'Maximum event temperature',
	eventMinTemp: 'Minimum event temperature',
	eventMinWet: 'Minimum event wet day index',
	eventMaxWet: 'Maximum event wet day index',
	months: {
		jan: 'Jan',
		feb: 'Feb',
		mar: 'Mar',
		apr: 'Apr',
		may: 'May',
		jun: 'Jun',
		jul: 'Jul',
		aug: 'Aug',
		sep: 'Sep',
		oct: 'Oct',
		nov: 'Nov',
		dec: 'Dec',
	},
	e404Title: 'Page not found',
	e404: 'The page you are looking for does not exist, please navigate to another page using the menus at the top of the page.',
	errorTitle: 'Error',
	error:
		'A problem has occurred.  If this keeps happening, please contact the system administrator.',
	yourRegions: 'Your regions',
	uploadRegion: 'Upload region',
	uploadRegionTooltip: 'Upload a GeoJSON file containing polygon regions',
	userRegionButton: 'Explore events in uploaded region',
	selectUserRegionFeature: 'Click a region outline to select it',
	deleteRegion: 'Remove region',
	regionLimitReached: 'Region limit reached (3/3). Merge into an existing region?',
	mergeIntoRegion: 'Merge into',
	mergeConfirm: 'Merge',
	mergeCancel: 'Cancel',
	uploadErrorInvalidJson: 'Invalid JSON — the file could not be parsed.',
	uploadErrorNotGeoJson: 'File does not contain a GeoJSON Feature or FeatureCollection.',
	uploadErrorNoPolygons: 'No polygon or multipolygon features found in the file.',
	uploadErrorTooLarge:
		'This region is too large to save in your browser. Try simplifying the geometry (fewer points) and upload again.',
}

type Labels = typeof labelsEn

const labels: Record<Language, Labels> = {
	en: labelsEn,
}

// Locale definitions from here: https://github.com/d3/d3-time-format/tree/main/locale
const enLocale: TimeLocaleDefinition = {
	dateTime: '%a %e %b %X %Y',
	date: '%d/%m/%Y',
	time: '%H:%M:%S',
	periods: ['AM', 'PM'],
	days: [
		'Sunday',
		'Monday',
		'Tuesday',
		'Wednesday',
		'Thursday',
		'Friday',
		'Saturday',
	],
	shortDays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
	months: [
		'January',
		'February',
		'March',
		'April',
		'May',
		'June',
		'July',
		'August',
		'September',
		'October',
		'November',
		'December',
	],
	shortMonths: [
		'Jan',
		'Feb',
		'Mar',
		'Apr',
		'May',
		'Jun',
		'Jul',
		'Aug',
		'Sep',
		'Oct',
		'Nov',
		'Dec',
	],
}

const locales: Record<Language, TimeLocaleDefinition> = {
	en: enLocale,
}

const LabelsKey: InjectionKey<ComputedRef<Labels>> = Symbol('labels')

function useLabels() {
	return inject(
		LabelsKey,
		computed(() => labels.en),
	)
}

function createI18n(langFunc: () => Language) {
	return (app: App) =>
		app.provide(
			LabelsKey,
			computed(() => labels[langFunc()]),
		)
}

export { createI18n, labels, langNames, locales, useLabels }
