services:
  pipeline:
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: c3s-pyenv:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.python
    env_file:
      - ../docker/.env
    volumes:
      - ./:/app:ro  # Mount process scripts into container
      - /Users/guy/Data/c3s-attribution/:/data:rw
      - /Users/guy/.cdsapirc:/root/.cdsapirc:ro
      - /Users/guy/Data/c3s-attribution/testout:/output:rw
    working_dir: /app
    environment:
      - EVENT_INPUT_DIR=/data
      - EVENT_OUTPUT_DIR=/output
    command: ["/bin/bash", "-c", "\
        micromamba run -n c3s-pyenv python3 run_pipeline.py \
    "]
