name: Build & push to Harbor

on:
  workflow_dispatch:
    inputs:
      ref_to_deploy:
        description: "Branch or tag to build"
        required: true
        default: "main"
      environment:
        description: "Deployment environment (dev, prod, etc)"
        required: true
        default: "dev"
      image_tag:
        description: "Image tag (optional, defaults to commit SHA)"
        required: false
jobs:
  build_and_push:
    name: Build and push image to Harbor
    uses: ecmwf/reusable-workflows/.github/workflows/build-and-push-image.yml@main
    with:
      ref: ${{ github.event.inputs.ref_to_deploy }}
      registry: eccr.ecmwf.int
      image_repository: c3s-applications/c3s-extreme-events-app
      image_tag: ${{ github.event.inputs.image_tag }}
      context: ./viewer
      dockerfile: ./viewer/Dockerfile
      environment_file: viewer/.env.${{ github.event.inputs.environment }}
      # build_args: |
      #   environment=${{ github.event.inputs.environment }}
    secrets:
      registry_username: ${{ secrets.HARBOR_USERNAME }}
      registry_password: ${{ secrets.HARBOR_PASSWORD }}

